<?php
$servidor="localhost";
$usuario="root";
$password="";
$bdd="internet";
$conexion=mysqli_connect($servidor,$usuario,$password,$bdd);
mysqli_select_db($conexion,$bdd);
mysqli_set_charset($conexion,"utf8");
?>